In [1]:
import camelot
import pandas as pd

# Updated Process

## 1. Create empty dataframe with proper column names

In [2]:
# This is where data will be added after cleaning. The final dataframe for export

In [3]:
df = pd.DataFrame(columns = [
    "Wissenschaftlicher_Name",
    "BE", 
    "BB", 
    "DE", 
    "GS",
    "H",
    "Vorzugs-habitate ",
    "Biol_ökol_Typ",
    "Gefährdungsursachen"
])
df

Empty DataFrame
Columns: [Wissenschaftlicher_Name, BE, BB, DE, GS, H, Vorzugs-habitate , Biol_ökol_Typ, Gefährdungsursachen]
Index: []

In [4]:
df.shape

(0, 9)

## 2. Setup mechanism to store accuracy report : QA step

In [5]:
accuracy = []

## 3. Dictionary of dataframes on the go

In [6]:
# Dictionary to collect dataframes created from each table
d = {}

## 4. Adding the list of pages to be parsed

In [7]:
pages = []
i = 8
while i < 12:
    pages.append(i)
    i = i + 1
print(pages)

[8, 9, 10, 11]

## 5. Parsing through the pages

In [8]:
for i in pages:
    # print page number
    print (i)
    # create dataframe with page number
    d[i] = pd.DataFrame()
    #read the page
    tables = camelot.read_pdf('16_heuschreck_print.pdf', 
                              pages= str(i), 
                              flavor='lattice')
                              #edge_tol=1000, row_tol=10)
    # add the accuracy report
    accuracy.append(tables[0].parsing_report)
    # assign the first table to a dataframe
    d[i] = tables[0].df
    # check for rows with "ex" column 2 and get a list of indices for those rows
# ex_index = d[i][(d[i].iloc[:,1] == "0")].index #| (d[i].iloc[:,3] == "ex") ].index
    # only keep the rows if the index is in the ex_index
#    d[i] = d[i][(d[i].index.isin(ex_index))]
    # print the shape of the dataframe 
    # (check whether there are enough columns, if not change page reading parameters
    print(d[i].shape)
# Print Done once all pages are parsed
print ("Done")

8
(6, 9)
9
(17, 9)
10
(16, 9)
11
(17, 9)
Done

In [9]:
d[8] = d[8].drop([0], axis=0)
d[8]

,0,1,2,3,4,5,6,7,8
1,Arcyptera microptera (FISCHER \nVON WALDHEIM)*...,0,0,0,§§,-,"GT, H",xer,
2,Calliptamus italicus (LINNAEUS)* \nItalienisch...,0,1,1,§,-,"GT, H, LBS",xer,
3,Chorthippus albomarginatus (DE \nGEER) \nWeißr...,-,-,-,,h,"RS, G",,
4,Chorthippus apricarius (LINNAEUS) \nFeld-Grash...,-,-,V,,h,"RS, GA, \nGM, WG","(xer), \nmes",
5,Chorthippus biguttulus (LINNAEUS) \nNachtigall...,-,-,-,,h,"GT, GZ, \nWGT",(xer),

In [10]:
d[9] = d[9].drop([0], axis=0)
d[9]

,0,1,2,3,4,5,6,7,8
1,Chorthippus brunneus (THUN-\nBERG) \nBrauner G...,-,-,-,,sh,"RR, GT, H, \nO, LBS, PS, \nA",xer,
2,Chorthippus dorsatus (ZET-\nTERSTEDT) \nWiese...,-,-,-,,h,"GA, GF, \nGM, GT",,
3,Chorthippus mollis (CHARPENTIER) \nVerkannter ...,-,-,V,,h,"GT, GAT, H",xer,
4,Chorthippus montanus (CHARPEN-\nTIER)* \nSumpf...,2,3,V,,s,"M, GF, GAF",hyg,"2d, 6b, 7b, \n14a, 14e"
5,Chorthippus parallelus (ZET-\nTERSTEDT) \nGeme...,-,-,-,,h,"GM, GA, GI, \nGZ, LB",,
6,Chorthippus pullus (PHILIPPI)* \nKiesbank-Gras...,1,1,1,,ss,"GT, H, WR",xer,"7a, 13a, \n14e"
7,Chorthippus vagans (EVERS-\nMANN)* \nSteppengr...,1,2,3,,,"ss WK, GTS, \nWGT, ATK",xer,"7a, 11, \n12a, 14a, \n14e"
8,Chrysochraon dispar (GERMAR) \nGroße Goldschrecke,-,-,-,,h,"RSC, M, \nGF, GA",(hyg),
9,Conocephalus dorsalis (LATREIL-\nLE) \nKurzflü...,V,-,V,,mh,"FR, SR, M, \nGAF",hyg,"2d, 6b, 14a"
10,Conocephalus fuscus (THUNBERG) \nLangflüglige ...,-,-,-,,h,"RS, GAM, \nGAF, MEP",,
11,Decticus verrucivorus (LINNAEUS)* \nWarzenbeißer,1,V,3,,ss,"GT, GM, \nLBS",xer,"7a, 7b, 14e"
12,Gampsocleis glabra (HERBST)* \nHeideschrecke,0,0,1,§§,-,"GT, H",xer,
13,Gryllotalpa gryllotalpa (LINNAEUS)* \nMaulwurf...,G,V,2,,s,"G, M; P","hyg, \nmes","2d, 4b, 6a"
14,Gryllus campestris LINNAEUS* \nFeldgrille,1,V,3,,ss,"GT, H",xer,"7a, 8a, 11, \n13a"
15,Leptophyes punctatissima (BOSC) \nPunktierte Z...,-,-,-,,h,"B, WG, P, \nGSM, GAF",,
16,Meconema thalassinum (DE \nGEER) \nGemeine Eic...,-,-,-,,mh,"B, W, P",,

In [11]:
d[10] = d[10].drop([0], axis=0)
d[10]

,0,1,2,3,4,5,6,7,8
1,Metrioptera bicolor (PHILIPPI) \nZweifarbige B...,V,3,-,,"mh GT, H,","RSA, RSC, \nGAT",xer,"1a, 7, 8a, \n13a, 14e"
2,Metrioptera brachyptera (LIN-\nNAEUS)* \nKurzf...,0,2,-,,-,"M, GF",hyg,
3,Metrioptera roeselii (HAGENBACH) \nRoesels Bei...,-,-,-,,h,"RS, GF, \nGM, GA",,
4,Myrmecophilus acervorum (PAN-\nZER) \nAmeiseng...,-,G,D,,,"mh GT, H, R, O",par,
5,Myrmeleotettix maculatus (THUN-\nBERG) \nGefle...,V,-,-,,"mh GT, H",,xer,7a
6,Nemobius sylvestris (BOSC)* \nWaldgrille,G,V,-,,s,"B, WT","xer, \nmes","11b, 13a"
7,Oedipoda caerulescens (LIN-\nNAEUS) \nBlauflüg...,V,-,3,§,"mh GTS, H,","OVG, OAA, \nA",xer,"1a, 7a, 8a, \n12a, 13a, \n14e"
8,Omocestus haemorrhoidalis \n(CHARPENTIER) \nRo...,V,-,V,,,"mh GTS, GAT, \nH",xer,"1a, 7a, \n13a, 14e"
9,Omocestus viridulus (LINNAEUS)* \nBunter Grash...,2,V,-,,s,"M, GF",hyg,"2d, 7b, 14e"
10,Pholidoptera griseoaptera (DE \nGEER) \nGewöhn...,-,-,-,,,"mh WG, B, GA",,
11,Platycleis albopunctata (GOEZE) \nWestliche Be...,V,-,V,,,"mh GT, H, ADO",xer,"2, 7, 8, 13a"
12,Platycleis montana (KOLLAR)* \nSteppen-Beißsch...,0,1,1,§§,-,"GT, H",xer,
13,Psophus stridulus (LINNAEUS)* \nRotflüglige Sc...,0,1,2,§,-,"GT, H",xer,
14,Sphingonotus caerulans (LIN-\nNAEUS)* \nBlaufl...,1,3,2,§,ss,"GTS, AT, \nRRS, OAA, \nATK",xer,"7a, 8a, \n12a, 13a, \n14a, 14e"
15,Stauroderus scalaris (FISCHER \nVON WALDHEIM)*...,0,0,2,,-,"GT, H",xer,"1a, 7a"

In [12]:
d[11] = d[11].drop([0], axis=0)
d[11]

,0,1,2,3,4,5,6,7,8
1,Stenobothrus lineatus (PANZER)* \nHeidegrashüpfer,3,3,V,,"mh GT, H",,xer,7a
2,Stenobothrus nigromaculatus \n(HERRICH-SCHÄFFE...,0,1,2,,-,"GT, H",xer,
3,Stenobothrus stigmaticus (RAM-\nBUR)* \nKleine...,1,1,2,,-,GT,xer,
4,Stethophyma grossum (LINNAEUS) \nSumpfschrecke,V,V,-,,mh,"FR, M, GF, \nGAF",hyg,"2d, 6b, 7b"
5,Tetrix subulata (LINNAEUS) \nSäbeldornschrecke,-,-,-,,mh,"FP, GF, \nGAF, M, \nSW",hyg,
6,Tetrix tenuicornis (SAHLBERG)* \nLangfühler-Do...,G,G,-,,s,"GT, H, AT",xer,"7, 11a, \n13a, 14e"
7,Tetrix undulata (SOWERBY) \nGemeine Dornschrecke,-,-,-,,mh,"FP, RR, G, \nAT, SW",,
8,Tettigonia cantans (FUESSLY)* \nZwitscherschrecke,1,3,-,,ss,"GA, GS, \nWG, B",hyg,"2a, 2d, 6a, \n6b, 14e"
9,Tettigonia caudata (CHARPEN-\nTIER)* \nÖstlich...,1,V,-,,ss,"GA, GS, RS",xer,"1c, 2a, 14e"
10,Tettigonia viridissima LINNAEUS \nGrünes Heupferd,-,-,-,,h,"B, GA, GS, \nLB, P, RSB, \nWG",,
11,Nicht etablierte oder nicht im Freiland etabli...,,,,,,,,
12,Acheta domesticus (LINNAEUS) \nHeimchen,ne,-,ne,,,,syn,
13,Anacridium aegyptium (LIN-\nNAEUS)* \nÄgyptisc...,ne,ne,ne,,-,,syn,
14,Barbitistes serricauda (FABRICUS)* \nLaubholz-...,ne,ne,-,,-,,,
15,Leptophyes albovittata (KOLLAR)* \nGestreifte ...,ne,R,-,,-,,,
16,Locusta migratoria LINNAEUS* \nEuropäische Wan...,ne,ne,0,,-,,,

In [13]:
# Check accuracy reports for the process
accuracy

[{'accuracy': 100.0, 'whitespace': 16.67, 'order': 1, 'page': 8},
 {'accuracy': 99.86, 'whitespace': 19.61, 'order': 1, 'page': 9},
 {'accuracy': 98.35, 'whitespace': 16.67, 'order': 1, 'page': 10},
 {'accuracy': 99.15, 'whitespace': 29.41, 'order': 1, 'page': 11}]

# Data cleanup steps

d[67]       
    : Look at the data frame extracted from 67th page
d[67].shape 
    : Look at the shape of the dataframe
d[68] = d[68].drop([12], axis=1)
    : Drop the 12th column in place
d[68][10] = d[68][[10, 11]].agg(' '.join, axis=1)
    : Join 10th and 11th columns with a space in between
d[69][[9,11]] = d[69][9].str.split('\n', expand=True)
    : Split 9th Column at the '\n' sign and add a new column called 11
column_to_move = d[69].pop(11)
column_to_move
d[69].insert(9, 11, column_to_move )
    : Pop column 11 and insert it at column 9
d[75].insert(9, '10', ["",""])
    : Insert two rows of column 10 after 9 with empty cells

In [14]:
# Check whether all dataframes are of the same size
for key in d:
    print(key)
    print(d[key].shape)

8
(5, 9)
9
(16, 9)
10
(15, 9)
11
(16, 9)

In [15]:
# Removing empty dataframes
# del d[64]
# del d[74]

In [16]:
# Creates a sorted dictionary (sorted by key)
from collections import OrderedDict
d2 = OrderedDict(sorted(d.items()))

In [17]:
# Check whether the dictionary is sorted
for key in d2:
    print(key)

8
9
10
11

In [18]:
# Rename all the dataframes in the sorted dictionary
for key in d2:
    print(key)
    d2[key].columns = [ "Wissenschaftlicher_Name",
    "BE", 
    "BB", 
    "DE", 
    "GS",
    "H",
    "Vorzugs-habitate ",
    "Biol_ökol_Typ",
    "Gefährdungsursachen"]
print("Rename completed for concat")

8
9
10
11
Rename completed for concat

In [19]:
# Concatanate all the non-empty dataframes in the sorted dictionary into the empty df
for key in d2:
    df = pd.concat([df, d2[key]], axis = 0)
df

,Wissenschaftlicher_Name,BE,BB,DE,GS,H,Vorzugs-habitate,Biol_ökol_Typ,Gefährdungsursachen
1,Arcyptera microptera (FISCHER \nVON WALDHEIM)*...,0,0,0,§§,-,"GT, H",xer,
2,Calliptamus italicus (LINNAEUS)* \nItalienisch...,0,1,1,§,-,"GT, H, LBS",xer,
3,Chorthippus albomarginatus (DE \nGEER) \nWeißr...,-,-,-,,h,"RS, G",,
4,Chorthippus apricarius (LINNAEUS) \nFeld-Grash...,-,-,V,,h,"RS, GA, \nGM, WG","(xer), \nmes",
5,Chorthippus biguttulus (LINNAEUS) \nNachtigall...,-,-,-,,h,"GT, GZ, \nWGT",(xer),
1,Chorthippus brunneus (THUN-\nBERG) \nBrauner G...,-,-,-,,sh,"RR, GT, H, \nO, LBS, PS, \nA",xer,
2,Chorthippus dorsatus (ZET-\nTERSTEDT) \nWiese...,-,-,-,,h,"GA, GF, \nGM, GT",,
3,Chorthippus mollis (CHARPENTIER) \nVerkannter ...,-,-,V,,h,"GT, GAT, H",xer,
4,Chorthippus montanus (CHARPEN-\nTIER)* \nSumpf...,2,3,V,,s,"M, GF, GAF",hyg,"2d, 6b, 7b, \n14a, 14e"
5,Chorthippus parallelus (ZET-\nTERSTEDT) \nGeme...,-,-,-,,h,"GM, GA, GI, \nGZ, LB",,
6,Chorthippus pullus (PHILIPPI)* \nKiesbank-Gras...,1,1,1,,ss,"GT, H, WR",xer,"7a, 13a, \n14e"
7,Chorthippus vagans (EVERS-\nMANN)* \nSteppengr...,1,2,3,,,"ss WK, GTS, \nWGT, ATK",xer,"7a, 11, \n12a, 14a, \n14e"
8,Chrysochraon dispar (GERMAR) \nGroße Goldschrecke,-,-,-,,h,"RSC, M, \nGF, GA",(hyg),
9,Conocephalus dorsalis (LATREIL-\nLE) \nKurzflü...,V,-,V,,mh,"FR, SR, M, \nGAF",hyg,"2d, 6b, 14a"
10,Conocephalus fuscus (THUNBERG) \nLangflüglige ...,-,-,-,,h,"RS, GAM, \nGAF, MEP",,
11,Decticus verrucivorus (LINNAEUS)* \nWarzenbeißer,1,V,3,,ss,"GT, GM, \nLBS",xer,"7a, 7b, 14e"
12,Gampsocleis glabra (HERBST)* \nHeideschrecke,0,0,1,§§,-,"GT, H",xer,
13,Gryllotalpa gryllotalpa (LINNAEUS)* \nMaulwurf...,G,V,2,,s,"G, M; P","hyg, \nmes","2d, 4b, 6a"
14,Gryllus campestris LINNAEUS* \nFeldgrille,1,V,3,,ss,"GT, H",xer,"7a, 8a, 11, \n13a"
15,Leptophyes punctatissima (BOSC) \nPunktierte Z...,-,-,-,,h,"B, WG, P, \nGSM, GAF",,
16,Meconema thalassinum (DE \nGEER) \nGemeine Eic...,-,-,-,,mh,"B, W, P",,
1,Metrioptera bicolor (PHILIPPI) \nZweifarbige B...,V,3,-,,"mh GT, H,","RSA, RSC, \nGAT",xer,"1a, 7, 8a, \n13a, 14e"
2,Metrioptera brachyptera (LIN-\nNAEUS)* \nKurzf...,0,2,-,,-,"M, GF",hyg,
3,Metrioptera roeselii (HAGENBACH) \nRoesels Bei...,-,-,-,,h,"RS, GF, \nGM, GA",,
4,Myrmecophilus acervorum (PAN-\nZER) \nAmeiseng...,-,G,D,,,"mh GT, H, R, O",par,
5,Myrmeleotettix maculatus (THUN-\nBERG) \nGefle...,V,-,-,,"mh GT, H",,xer,7a
6,Nemobius sylvestris (BOSC)* \nWaldgrille,G,V,-,,s,"B, WT","xer, \nmes","11b, 13a"
7,Oedipoda caerulescens (LIN-\nNAEUS) \nBlauflüg...,V,-,3,§,"mh GTS, H,","OVG, OAA, \nA",xer,"1a, 7a, 8a, \n12a, 13a, \n14e"
8,Omocestus haemorrhoidalis \n(CHARPENTIER) \nRo...,V,-,V,,,"mh GTS, GAT, \nH",xer,"1a, 7a, \n13a, 14e"
9,Omocestus viridulus (LINNAEUS)* \nBunter Grash...,2,V,-,,s,"M, GF",hyg,"2d, 7b, 14e"
10,Pholidoptera griseoaptera (DE \nGEER) \nGewöhn...,-,-,-,,,"mh WG, B, GA",,
11,Platycleis albopunctata (GOEZE) \nWestliche Be...,V,-,V,,,"mh GT, H, ADO",xer,"2, 7, 8, 13a"
12,Platycleis montana (KOLLAR)* \nSteppen-Beißsch...,0,1,1,§§,-,"GT, H",xer,
13,Psophus stridulus (LINNAEUS)* \nRotflüglige Sc...,0,1,2,§,-,"GT, H",xer,
14,Sphingonotus caerulans (LIN-\nNAEUS)* \nBlaufl...,1,3,2,§,ss,"GTS, AT, \nRRS, OAA, \nATK",xer,"7a, 8a, \n12a, 13a, \n14a, 14e"
15,Stauroderus scalaris (FISCHER \nVON WALDHEIM)*...,0,0,2,,-,"GT, H",xer,"1a, 7a"
1,Stenobothrus lineatus (PANZER)* \nHeidegrashüpfer,3,3,V,,"mh GT, H",,xer,7a
2,Stenobothrus nigromaculatus \n(HERRICH-SCHÄFFE...,0,1,2,,-,"GT, H",xer,
3,Stenobothrus stigmaticus (RAM-\nBUR)* \nKleine...,1,1,2,,-,GT,xer,
4,Stethophyma grossum (LINNAEUS) \nSumpfschrecke,V,V,-,,mh,"FR, M, GF, \nGAF",hyg,"2d, 6b, 7b"
5,Tetrix subulata (LINNAEUS) \nSäbeldornschrecke,-,-,-,,mh,"FP, GF, \nGAF, M, \nSW",hyg,
6,Tetrix tenuicornis (SAHLBERG)* \nLangfühler-Do...,G,G,-,,s,"GT, H, AT",xer,"7, 11a, \n13a, 14e"
7,Tetrix undulata (SOWERBY) \nGemeine Dornschrecke,-,-,-,,mh,"FP, RR, G, \nAT, SW",,
8,Tettigonia cantans (FUESSLY)* \nZwitscherschrecke,1,3,-,,ss,"GA, GS, \nWG, B",hyg,"2a, 2d, 6a, \n6b, 14e"
9,Tettigonia caudata (CHARPEN-\nTIER)* \nÖstlich...,1,V,-,,ss,"GA, GS, RS",xer,"1c, 2a, 14e"
10,Tettigonia viridissima LINNAEUS \nGrünes Heupferd,-,-,-,,h,"B, GA, GS, \nLB, P, RSB, \nWG",,
11,Nicht etablierte oder nicht im Freiland etabli...,,,,,,,,
12,Acheta domesticus (LINNAEUS) \nHeimchen,ne,-,ne,,,,syn,
13,Anacridium aegyptium (LIN-\nNAEUS)* \nÄgyptisc...,ne,ne,ne,,-,,syn,
14,Barbitistes serricauda (FABRICUS)* \nLaubholz-...,ne,ne,-,,-,,,
15,Leptophyes albovittata (KOLLAR)* \nGestreifte ...,ne,R,-,,-,,,
16,Locusta migratoria LINNAEUS* \nEuropäische Wan...,ne,ne,0,,-,,,

In [20]:
df.describe()

,Wissenschaftlicher_Name,BE,BB,DE,GS,H,Vorzugs-habitate,Biol_ökol_Typ,Gefährdungsursachen
count,52,52,52,52,52,52,52,52,52
unique,52,9,10,9,3,10,38,10,21
top,Arcyptera microptera (FISCHER \nVON WALDHEIM)*...,-,-,-,,-,,xer,
freq,1,17,22,25,45,13,8,23,31

In [21]:
df2 = df.loc[df["BE"] == "0"]
df2

,Wissenschaftlicher_Name,BE,BB,DE,GS,H,Vorzugs-habitate,Biol_ökol_Typ,Gefährdungsursachen
1,Arcyptera microptera (FISCHER \nVON WALDHEIM)*...,0,0,0,§§,-,"GT, H",xer,
2,Calliptamus italicus (LINNAEUS)* \nItalienisch...,0,1,1,§,-,"GT, H, LBS",xer,
12,Gampsocleis glabra (HERBST)* \nHeideschrecke,0,0,1,§§,-,"GT, H",xer,
2,Metrioptera brachyptera (LIN-\nNAEUS)* \nKurzf...,0,2,-,,-,"M, GF",hyg,
12,Platycleis montana (KOLLAR)* \nSteppen-Beißsch...,0,1,1,§§,-,"GT, H",xer,
13,Psophus stridulus (LINNAEUS)* \nRotflüglige Sc...,0,1,2,§,-,"GT, H",xer,
15,Stauroderus scalaris (FISCHER \nVON WALDHEIM)*...,0,0,2,,-,"GT, H",xer,"1a, 7a"
2,Stenobothrus nigromaculatus \n(HERRICH-SCHÄFFE...,0,1,2,,-,"GT, H",xer,

In [22]:
df2.reset_index(inplace = True)
df2 = df2.drop(['index'], axis=1)
df2

,Wissenschaftlicher_Name,BE,BB,DE,GS,H,Vorzugs-habitate,Biol_ökol_Typ,Gefährdungsursachen
0,Arcyptera microptera (FISCHER \nVON WALDHEIM)*...,0,0,0,§§,-,"GT, H",xer,
1,Calliptamus italicus (LINNAEUS)* \nItalienisch...,0,1,1,§,-,"GT, H, LBS",xer,
2,Gampsocleis glabra (HERBST)* \nHeideschrecke,0,0,1,§§,-,"GT, H",xer,
3,Metrioptera brachyptera (LIN-\nNAEUS)* \nKurzf...,0,2,-,,-,"M, GF",hyg,
4,Platycleis montana (KOLLAR)* \nSteppen-Beißsch...,0,1,1,§§,-,"GT, H",xer,
5,Psophus stridulus (LINNAEUS)* \nRotflüglige Sc...,0,1,2,§,-,"GT, H",xer,
6,Stauroderus scalaris (FISCHER \nVON WALDHEIM)*...,0,0,2,,-,"GT, H",xer,"1a, 7a"
7,Stenobothrus nigromaculatus \n(HERRICH-SCHÄFFE...,0,1,2,,-,"GT, H",xer,

In [23]:
df2.describe()

,Wissenschaftlicher_Name,BE,BB,DE,GS,H,Vorzugs-habitate,Biol_ökol_Typ,Gefährdungsursachen
count,8,8,8,8,8,8,8,8,8
unique,8,1,3,4,3,1,3,2,2
top,Arcyptera microptera (FISCHER \nVON WALDHEIM)*...,0,1,1,§§,-,"GT, H",xer,
freq,1,8,4,3,3,8,6,7,7

In [26]:
# updated export location
# export the dataframe as CSV
df2.to_csv('../../../Transformation/Raw_csv/Grasshoppers_crickets.csv', 
           index=False)