In [92]:
import pandas as pd

In [93]:
df_1 = pd.read_csv('first_30 - first_30.csv')

In [94]:
df_2 = pd.read_csv('second_31_60 - second_31_60.csv')

In [95]:
df_3 = pd.read_csv('third_61_89 - third_61_89.csv')

In [96]:
final_df = pd.concat([df_1, df_2, df_3], axis=0)

In [97]:
final_df.describe()

,Gattung,Artname,BE,Bestand,Vor_1990,1990_2017,Trend_kurz,Habitat,D,BB,GS,Deutscher_name
count,153,153,153,153,153,152,4,153,153,153,47,153
unique,126,153,4,1,55,4,3,69,9,3,5,153
top,"Eupithecia CURTIS, 1825","fusconebulosa (DEGEER, 1778)",0,ex,x vor 1900,–,declining,TR,2,⬤,§,Adlerfarn-Wurzelbohrer
freq,5,1,100,153,38,149,2,18,38,124,26,1

In [98]:
final_df.head()

,Gattung,Artname,BE,Bestand,Vor_1990,1990_2017,Trend_kurz,Habitat,D,BB,GS,Deutscher_name
0,"Pharmacis HÜBNER, 1820","fusconebulosa (DEGEER, 1778)",0,ex,x 1973,–,NaN,LKW,V,⬤,NaN,Adlerfarn-Wurzelbohrer
1,"Heterogenea KNOCH, 1783","asella (DEN. & SCHIFF., 1775)",0,ex,x 1978,–,NaN,LMW,V,⬤,NaN,Kleiner Schneckenspinner
2,"Zygaena FABRICIUS, 1775","purpuralis (BRUENNICH, 1763)",0,ex,x,–,NaN,TR,V,⬤,§,Thymian-Widderchen
3,"Malacosoma HÜBNER, 1820","castrensis (LINNAEUS, 1758)",0,ex,x 1982,–,NaN,TR,3,⬤,§,Wolfsmilch-Ringelspinner
4,"Eriogaster GERMAR, 1810","lanestris (LINNAEUS, 1758)",0,ex,x vor 1900,–,NaN,WRS,3,⬤,§,Wollafter

In [99]:
final_df.loc[(final_df["BE"] == "0") | (final_df["BE"] == 0)].describe()

,Gattung,Artname,BE,Bestand,Vor_1990,1990_2017,Trend_kurz,Habitat,D,BB,GS,Deutscher_name
count,150,150,150,150,150,149,4,150,150,150,47,150
unique,124,150,2,1,53,4,3,68,8,3,5,150
top,"Eupithecia CURTIS, 1825","fusconebulosa (DEGEER, 1778)",0,ex,x vor 1900,–,declining,TR,2,⬤,§,Adlerfarn-Wurzelbohrer
freq,5,1,100,150,38,146,2,18,38,122,26,1

In [100]:
# Remove the three species with Bestand == ex but BE is not 0. 
# Based on author correspondance.
final = final_df.loc[(final_df["BE"] == "0") | (final_df["BE"] == 0)]

In [101]:
final.describe()

,Gattung,Artname,BE,Bestand,Vor_1990,1990_2017,Trend_kurz,Habitat,D,BB,GS,Deutscher_name
count,150,150,150,150,150,149,4,150,150,150,47,150
unique,124,150,2,1,53,4,3,68,8,3,5,150
top,"Eupithecia CURTIS, 1825","fusconebulosa (DEGEER, 1778)",0,ex,x vor 1900,–,declining,TR,2,⬤,§,Adlerfarn-Wurzelbohrer
freq,5,1,100,150,38,146,2,18,38,122,26,1

In [102]:
final["BE"] = "0"

/var/folders/sf/pjcpsvqj67b_pqmm82g4y8bm0000gq/T/ipykernel_97496/282753805.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final["BE"] = "0"

In [103]:
final["BE"].unique()

array(['0'], dtype=object)

In [104]:
final

,Gattung,Artname,BE,Bestand,Vor_1990,1990_2017,Trend_kurz,Habitat,D,BB,GS,Deutscher_name
0,"Pharmacis HÜBNER, 1820","fusconebulosa (DEGEER, 1778)",0,ex,x 1973,–,NaN,LKW,V,⬤,NaN,Adlerfarn-Wurzelbohrer
1,"Heterogenea KNOCH, 1783","asella (DEN. & SCHIFF., 1775)",0,ex,x 1978,–,NaN,LMW,V,⬤,NaN,Kleiner Schneckenspinner
2,"Zygaena FABRICIUS, 1775","purpuralis (BRUENNICH, 1763)",0,ex,x,–,NaN,TR,V,⬤,§,Thymian-Widderchen
3,"Malacosoma HÜBNER, 1820","castrensis (LINNAEUS, 1758)",0,ex,x 1982,–,NaN,TR,3,⬤,§,Wolfsmilch-Ringelspinner
4,"Eriogaster GERMAR, 1810","lanestris (LINNAEUS, 1758)",0,ex,x vor 1900,–,NaN,WRS,3,⬤,§,Wollafter
...,...,...,...,...,...,...,...,...,...,...,...,...
51,"Xestia HÜBNER, 1818","stigmatica (HÜBNER, 1813)",0,ex,x vor 1900,–,NaN,BuW,*,⬤,NaN,Rhombus-Bodeneule
52,"Xestia HÜBNER, 1818","castanea (ESPER, 1798)",0,ex,x vor 1900,–,NaN,CH,3,⬤,NaN,Ginsterheiden-Bodeneule
53,"Xestia HÜBNER, 1818","ashworthii (DOUBLEDAY, 1855)",0,ex,x vor 1900,–,NaN,"WRS, WS",2,⬤,NaN,Aschgraue Bodeneule
54,"Eugraphe HÜBNER, 1821","sigma (DEN. & SCHIFF., 1775)",0,ex,x vor 1900,–,NaN,KWB,2,⬤,NaN,Sigma-Bodeneule
55,"Protolampra MCDUNNOUGH, 1929","sobrina (DUPONCHEL, 1843)",0,ex,x vor 1900,–,NaN,"CH, KWB",2,⬤,NaN,Heidemoor-Bodeneule

In [105]:
final["BE"].unique()

array(['0'], dtype=object)

In [107]:
# Update export location
# Export the final collated csv
final.to_csv('../../../Transformation/Raw_csv/Butterflies_and_moths_final.csv', 
                index=False)